<?php
namespace  app\admin\controller;
use think\Controller;

class Administrator  extends  Common
{
    protected  $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Administrator();
    }

    /**
     * @return mixed*
     * 管理员首页
     */
    public function index()
    {
        $data = db('user')->select();
        //dump($data);
        $this->assign('data',$data);
        return $this->fetch();
    }

    /**
     * @return mixed
     * 管理员添加
     */
    public function add()
    {
        if (request()->isPost())
        {
           //halt(input('post.'));
            $res = $this->db->add(input('post.'));
            if($res['vaid'])
            {
                $this->success($res['aa'],'Administrator/index');exit;

            }
            else{
                $this->error($res['aa']);exit;
            }
        }
        return $this->fetch();
    }

    /***
     * @return mixed
     * 管理员编辑
     */
    public function upd()
    {
        $id = input('param.id');
       // halt($id);
        $oldData = $this->db->find($id);
        //halt($olddata);
        $this->assign('oldData',$oldData);
        if (request()->isPost())
        {
            //halt(input('post.'));
            $res = $this->db->upd(input('post.'));
            if($res['vaid'])
            {
                $this->success($res['message'],'Administrator/index');exit;

            }
            else{
                $this->error($res['message']);exit;
            }
        }
        return $this->fetch();
    }

    /**
     * @throws \think\Exception
     * 管理员删除
     */
    public function del()
    {
       //echo 1;die;
        $id = input('get.id');
       // halt($id);
       $res =  db('user')->where('id',$id)->delete();
        if($res)
        {
            $this->success('操作成功','index');exit;
        }
        else{
            $this->error('操作失败');exit;
        }
    }
    /**
     * 搜索
     */
    public function search()
    {
        if(request()->isPost())
        {
           $key = input('param.search');
           // halt($key);
           $data =  db('user')->where('id|uname|tel|email','like',"{$key}%")->select();
         //halt($a);
        }
        $this->assign('data',$data);
       return $this->fetch();
    }
}