<?php
namespace app\api\controller;
use think\Controller;
class Category extends Controller{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    public function getCategoryByParentId()
    {
        $id = input("post.id");
         //  halt($id);
        if (!intval($id)) {
            $this->error();
        }
        $category= $this->db->getCategoryByParentId($id);

        if ($category) {
            return show(1, "success", $category);
            // $this->success("成功");
        } else {
            $this->error("失败");
        }

        }
}